on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: CI
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tchx84/test-gnome-flatpak-app-action:v50
      options: --privileged
    steps:
    - uses: actions/checkout@v6
    - uses: tchx84/test-gnome-flatpak-app-action@v50
      with:
        manifest: com.github.tchx84.Flatseal.json
